# Generated by Django 4.0.2 on 2022-02-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='name',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
