# Generated by Django 4.0.2 on 2022-02-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_expenses_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='name',
        ),
    ]
